##################
# Package metadata. Unless you are forking, this shouldn't change.
# These are used to fill templated variables inside files (eg: {PUKE-FOO-BAR})
# and in some cases to construct build / deploy paths
##################
baseYank:
  package:
    # Code name (eg: {PUKE-PACKAGE-NAME})
      name: jsboot.js
    # Version  (eg: {PUKE-PACKAGE-VERSION})
      version: '0.2.0'
  rights:
    # License link (eg: {PUKE-RIGHTS-LICENSE})
      license: '<a href="http://www.gnu.org/licenses/agpl-3.0.html">Afero GPL</a>'
    # Copyright to be replaced in files (eg: {PUKE-RIGHTS-COPYRIGHT})
      copyright: 'All rights reserved <a href="http://www.webitup.fr">Â© Web It Up</a>'
    # Author (eg: {PUKE-RIGHTS-AUTHOR})
      author: '<a href="mailto:dev@webitup.fr">Mangled Deutz & Raildecom</a>'
  git:
    # Repository base url (eg: {PUKE-GIT-ROOT})
      root: 'https://github.com/jsBoot/jsboot.js/blob/master/src'

##################
# Platform dependent stuff
# These specify build- / run- time paths.
# You should override them either by adding a config-USERNAME-UNAME node in this file
# or by creating a config-USERNAME-UNAME.json file and adding a "userYank" node in it.
##################
defaultYank:
  # Base root path against which relative paths may be resolved
  # ROOT: '${HOME}/buildd'
  root: './'

  # Specific paths - if using a relative path, will be resolved against "root"
  # You may mix env variables as well (${HOME}) - see puke documentation for more
  paths:
      build: 'tmp'
      deploy: 'lib'
      doc: 'doc'

  links:
    airstrip:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    self:
      url: '//static.sn.ackitup.net/lib/webitup'

  settings:
      # Instruct puke to copy trunk versions of the shims - only of use for me:
      # VARIANT: "bleed"
      variant: "bleednot"



##################
# Private for contributors and wiu deployment needs
##################

# Integration
config-jenkins-linux:
  # ROOT: '/opt/puke/jenkins-roxee'
  paths:
    deploy: '/var/www/deploy/static/lib/webitup'
  # DOC_ROOT: '/var/www/deploy/static/doc/spitfire'
  links:
    airstrip:
      version: '1.0'
      url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    self:
      url: '//static.sn.ackitup.net/lib/webitup'


# Roxee box
config-www-data-linux:
  paths:
    deploy: '/home/lxxl-deploy/lxxl'
  links:
    airstrip:
      version: '1.0'
      url: 'https://www.education-et-numerique.fr/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://www.education-et-numerique.fr/spitfire.json'
    self:
      url: '//www.education-et-numerique.fr/'

config-dmp-darwin:
  root: "${HOME}/buildd/stage.webitup.org"
  paths:
    deploy: "${HOME}/buildd/deploy.webitup.org/web/static/lib/webitup"

  links:
    airstrip:
      version: '1.0'
      url: 'http://static.loft.sn.ackitup.net:4242/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'http://static.loft.sn.ackitup.net:4242/lib/webitup/spitfire.json'
    self:
      url: '//static.loft.sn.ackitup.net:4242/lib/webitup'

# Raildecom workin
config-raildecom-darwin:
  paths:
    deploy: '${HOME}/workspace/webitup/deploy/static/lib/webitup'
  links:
    airstrip:
      version: '1.0'
      url: 'https://static.sn.ackitup.net/airstrip.json'
    spitfire:
        version: '1.0'
        url: 'https://static.sn.ackitup.net/lib/webitup/spitfire.json'
    self:
      url: '//static.sn.ackitup.net/lib/webitup'

    # PUBLIC: '//static.loft.sn.ackitup.net:4242/lib/webitup'
    # PUBLIC: '//app.roxee.net/lib/webitup'

